version: '3'

volumes:
  db-data:

services:
  db:
    image: postgres:11.5
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    command: /bin/bash -c "rm -rf tmp/pids/server.pid; bundle exec rails s -p 8080 -b 0.0.0.0"
    volumes:
      - ./backend:/app/backend
    ports:
      - '8080:8080'
    depends_on:
      - db
    tty: true
    stdin_open: true

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app/frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    tty: true
